site_name: Test internal projects
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    primary: black
    accent: light blue
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline 
  #       name: Switch to dark mode
  #     primary: teal
  #     accent: purple 
  #   - scheme: slate 
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode    
  #     primary: teal
  #     accent: lime

plugins:
  - social
  - search
  # - glightbox

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://softteco.com/"  target="_blank" rel="noopener">Test</a>
