name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
      - run: npm install -g staticrypt
      - run: find $READTHEDOCS_OUTPUT/html -type f -name "*.html" -exec staticrypt {} --short \;
      - run: cp -rf encrypted/* $READTHEDOCS_OUTPUT/html/
      #- run: mkdocs gh-deploy --force
